### PR TITLE
Centralize paths to binaries

### PR DESCRIPTION
**Pull request by sean-**
Don't rely on PATH being passed to nad.  Refactored the installation scripts accordingly.

Let this pull request marinate for a day or two before merging.

### CODE REVIEW

**Comment by esproul** [comment]
Sean,
Thanks for doing this; I just have a couple of nits, but overall I like it.

1. plugins/freebsd/cpu.sh, line 1: possibly a left-over '--' from testing?

2. FreeBSD's /bin/sh has a printf built-in-- should we leave usage that alone, and avoid forking additional processes for that?

**Comment by sean-** [comment]
The -- is left habit from security hardening and is still recommended.  From `sh(1)`:

> A ``--'' or plain `-' will stop option processing and will force
> the remaining words on the command line to be treated as arguments.

I still consider it `sh(1)` best practice to have that hanging out, but my knowledge may be dated.  Speaking of, I added a new preamble to common.sh.

TIL: FreeBSD's `sh(1)` has `printf` built-in.

Updated.

**Comment by sean-** [comment]
Alright, I think I'm done with this for a day or two unless there is something more you want to see done.  Again, give it a day or two before merging the pull request in case we find something else on our end.

**Comment by esproul** [comment]
TIL: BSD bc has -e.  ;)  Not even GNU bc has that.  Also wasn't aware of a sh other than bash that has $(()), so it's a banner day all 'round.  Changes look good to me.  Ping back when you're satisfied and we'll merge.

**Comment by sean-** [comment]
Alright, done testing in prod and have ported out a few misc typos and omissions.  You should be good to merge this now.

The only thing I do want to mention re: the move from `bc(1)` in a few places to `sh(1)`'s arithmetic is that `sh(1)` only does integer arithmetic, not floating point.  I didn't see anything that was floating point other than the division, which I kept using `bc(1)`, but in case something jumps out at you.  Thanks!

**Comment by esproul** [comment]
Unless I missed something, it looks like you only replaced usage of expr(1) with sh arithmetic, and both of those are integer-only, so we should be fine.

**Pull request merged**
