### PR TITLE
New linux/vm.sh script

### PR DESCRIPTION
**Pull request by maier**
* use /proc/meminfo (instead of free)
* add additional meminfo metrics
* tested on centos 5.4, 6.6, 7.2; ubuntu 12.04, 14.04, 16.04

### CODE REVIEW

**Comment by esproul** [comment]
@maier I get different values for memory total between the existing and new versions.  What are the units that you're getting from /proc/meminfo?  The current script uses bytes.

**Comment by rileyberton** [comment]
Looks good to me

**Comment by maier** [comment]
doh! my bad math

**Comment by esproul** [comment]
LGTM

**Pull request merged**
